[package]
name = "huddle"
version = "0.1.0"
authors = ["Joshua Miller <jshuasmiller@gmail.com>"]

[dependencies]
ncurses = "*"
lazy_static = "0.1.*"
getopts = "0.2"
rustc-serialize = "0.3"
log = "*"
env_logger = "*"
